# Exported from Render on 2026-06-06T02:23:40Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    databases:
    - name: biblioteca-db
      databaseName: library_oxrr
      user: admin
      plan: free
      region: oregon
      ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
      postgresMajorVersion: "18"
